// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhUA5i6ex4-ImUhdRd_do4E-kDd5nGCu0',
    appId: '1:875772186105:web:b251f48e3da90828ab4128',
    messagingSenderId: '875772186105',
    projectId: 'aeromedic-core',
    authDomain: 'aeromedic-core.firebaseapp.com',
    storageBucket: 'aeromedic-core.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn9g0bnd7-myen5x5X3ArMd8Lf_f_grf8',
    appId: '1:875772186105:android:fc48f38113845493ab4128',
    messagingSenderId: '875772186105',
    projectId: 'aeromedic-core',
    storageBucket: 'aeromedic-core.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhUA5i6ex4-ImUhdRd_do4E-kDd5nGCu0',
    appId: '1:875772186105:web:9b09765ed7e72542ab4128',
    messagingSenderId: '875772186105',
    projectId: 'aeromedic-core',
    authDomain: 'aeromedic-core.firebaseapp.com',
    storageBucket: 'aeromedic-core.firebasestorage.app',
  );
}
