; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
upload_protocol = esptool
monitor_raw = yes

build_flags = 
    -Icomponents/edge-impulse
    -Icomponents/edge-impulse/edge-impulse-sdk
    -Icomponents/edge-impulse/edge-impulse-sdk/classifier
    -Icomponents/edge-impulse/edge-impulse-sdk/dsp
    -Icomponents/edge-impulse/edge-impulse-sdk/porting
    -Icomponents/edge-impulse/edge-impulse-sdk/tensorflow
    -Icomponents/edge-impulse/model-parameters
    -Icomponents/edge-impulse/tflite-model
    -DEI_CLASSIFIER_DISABLE_ESP_DSP=1
    -DEI_DSP_IMAGE_DISABLE_ESP_DSP=1
    -w
    -Icomponents/edge-impulse
    -Icomponents/edge-impulse/edge-impulse-sdk
    -Icomponents/edge-impulse/edge-impulse-sdk/classifier
    -Icomponents/edge-impulse/edge-impulse-sdk/dsp
    -Icomponents/edge-impulse/edge-impulse-sdk/dsp/dsp_engines
    -Icomponents/edge-impulse/edge-impulse-sdk/porting
    -Icomponents/edge-impulse/edge-impulse-sdk/tensorflow
    -Icomponents/edge-impulse/model-parameters
    -Icomponents/edge-impulse/tflite-model
    -Icomponents/edge-impulse/edge-impulse-sdk/porting/espressif/esp-dsp/modules/common/include
    -Icomponents/edge-impulse/edge-impulse-sdk/porting/espressif/esp-dsp/modules/dotprod/include
    -Icomponents/edge-impulse/edge-impulse-sdk/porting/espressif/esp-dsp/modules/fft/include
    -Icomponents/edge-impulse/edge-impulse-sdk/porting/espressif/esp-dsp/modules/iir/include
    -Icomponents/edge-impulse/edge-impulse-sdk/porting/espressif/esp-dsp/modules/fir/include
    -Icomponents/edge-impulse/edge-impulse-sdk/porting/espressif/esp-dsp/modules/math/include
    -Icomponents/edge-impulse/edge-impulse-sdk/porting/espressif/esp-dsp/modules/matrix/include
    -w
